# syntax=docker/dockerfile:1

FROM golang:1.22-alpine

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY ./go.mod .
COPY ./go.sum .

RUN go mod download

COPY . ./

 COPY *.go ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /tenant-api

EXPOSE 80

# Run
CMD ["/tenant-api"]

