# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DB_HOST: localhost
  DB_PORT: 8000
  DB_USER: root
  DB_PASS: root
  DB_NAMESPACE: test
  DB_DATABASE: test

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Start SurrealDB
      uses: jvllmr/surrealdb-action@2.0.0
      with:
        surrealdb_port: 8000
        surrealdb_user: root
        surrealdb_password: root
        surrealdb_auth: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
